name: Quality checks
on: push

jobs: 
  check_name:
    name: Check that name is present in README
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: grep "Alvaro" README.md

  spellcheck:
    name: Run spellchecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rojopolis/spellcheck-github-actions@0.14.0
        name: Spellcheck
